### ISSUE TITLE
Broken link to `cann_backend_221010`

### ISSUE THREAD

**Issue by HaFred** [fengyuentau/opencv#12]
### Describe the doc issue

Hi @fengyuentau, I am reaching out regarding installing opencv with the CANN backend. So currently I am referring to [this wiki](https://github.com/opencv/opencv/wiki/Huawei-CANN-Backend) which suggests the branch `cann_backend_221010`. However, the branch seems to be gone now. Could you kindly point me to a workable branch for CANN and also kindly advise on the wiki documentation? 

Thanks a lot!

**Comment by fengyuentau** [comment]
Actually the code had been integrated into the main branch of opencv. Let me update the documentation instead.

**Comment by fengyuentau** [comment]
Ok. Documentation is updated just now. Thanks for reporting.
